# .github/FUNDING.yml
# Estos son los patrocinadores de Mea-Core Enterprise

github: [KronoxYT]
patreon: # Reemplazar con el nombre de usuario de Patreon
open_collective: # Reemplazar con el nombre del colectivo
ko_fi: # Reemplazar con el nombre de usuario de Ko-fi
custom: ["https://www.meacore.ai/sponsor"] # Reemplazar con una URL de patrocinio personalizada
