apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "mea-core.fullname" . }}
  labels:
    {{- include "mea-core.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  serviceName: {{ include "mea-core.fullname" . }}
  selector:
    matchLabels:
      {{- include "mea-core.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "mea-core.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          volumeMounts:
            - name: data
              mountPath: /app/data
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
  {{- if .Values.persistence.enabled }}
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: {{ .Values.persistence.storageClass | quote }}
      resources:
        requests:
          storage: {{ .Values.persistence.size | quote }}
  {{- end }}
