version: '3.8'

services:
  # Nodo principal del enjambre
  mea_core_1:
    build:
      context: ..
      dockerfile: Dockerfile
    container_name: mea_core_node_1
    ports:
      - "8001:8000" # Mapea el puerto 8000 del contenedor al 8001 del host
    volumes:
      - ../data:/app/data # Persistir los datos
    environment:
      - MEA_NODE_ID=node_1
      - MEA_SWARM_PEERS=ws://mea_core_2:8000,ws://mea_core_3:8000
    networks:
      - mea_swarm_net

  # Segundo nodo del enjambre
  mea_core_2:
    build:
      context: ..
      dockerfile: Dockerfile
    container_name: mea_core_node_2
    ports:
      - "8002:8000"
    volumes:
      - ../data:/app/data
    environment:
      - MEA_NODE_ID=node_2
      - MEA_SWARM_PEERS=ws://mea_core_1:8000,ws://mea_core_3:8000
    depends_on:
      - mea_core_1
    networks:
      - mea_swarm_net

  # Tercer nodo del enjambre
  mea_core_3:
    build:
      context: ..
      dockerfile: Dockerfile
    container_name: mea_core_node_3
    ports:
      - "8003:8000"
    volumes:
      - ../data:/app/data
    environment:
      - MEA_NODE_ID=node_3
      - MEA_SWARM_PEERS=ws://mea_core_1:8000,ws://mea_core_2:8000
    depends_on:
      - mea_core_1
      - mea_core_2
    networks:
      - mea_swarm_net

networks:
  mea_swarm_net:
    driver: bridge